[package]
org = "FiveStackDev"
name = "ResourceHub"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[platform]
target = "java11"

[[platform.libraries]]
groupId = "mysql"
artifactId = "mysql-connector-java"
version = "8.0.26"
