# Database configuration
[ResourceHub.database]
USER = "your_db_user"
PASSWORD = "your_db_password" 
HOST = "localhost"
PORT = 3306
DATABASE = "resourcehub"

# SMTP server configuration
[ResourceHub.common]
SMTP_HOST = "smtp.gmail.com"
SMTP_USER = "your_email@gmail.com"
SMTP_PASSWORD = "your_app_password"

# API keys
[ResourceHub.report]
PDFSHIFT_API_KEY = "your_pdfshift_api_key"
